name: Addon-release

on:
  push:
    tags:
      - "v*"

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        pip install scons markdown
        sudo apt update
        sudo apt install gettext

    - name: Build addon
      run: scons

    - name: Upload release
      id: release
      uses: softprops/action-gh-release@v2
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        tag_name: ${{ github.event_name == 'push' && github.ref_name || github.event.inputs.version }}
        files: |
          *.nvda-addon
        generate_release_notes: true
        prerelease: false

    - name: submit addon
      uses: beqabeqa473/submitNVDAAddon@master
      with:
        addon_name: 'speechFilter'
        addon_version: '0.1.1'
        download_url: ${{ fromJSON(steps.release.outputs.assets)[0].browser_download_url }}
        channel: 'alpha'
        token: ${{ secrets.USER_TOKEN }}
